### ISSUE TITLE
Getting list of attendees for the 2018-11-16 Industry Day meeting.

### ISSUE THREAD

**Issue by kfogel** [18F/tts-buy-cloud-support-services#3]
Thank you for the Support Services Industry Day meeting today.  It was very informative.

Will you be circulating a list of attendees?  (Either by emailing it around or by just posting the list to this repository -- obviously, since I filed this issue, I'm comfortable with either way :-) .)

**Comment by mogul** [comment]
I'm sorry we didn't reply to this previously! We did not circulate the attendee list. No particular reason; we just didn't have that as part of the plan for the day. We'll keep this in mind for next time as a thing that might be useful for attendees!

We've recently shifted to actively soliciting this RFQ and updated this repository accordingly. Please let us know in further issues if you have any questions about the RFQ.

**Comment by kfogel** [comment]
Thanks for the response, @mogul.  All sounds good; we'll look for the RFQ.
