### ISSUE TITLE
Question: Oral Interviews

### ISSUE THREAD

**Issue by icamp16** [18F/tts-buy-cloud-support-services#5]
# Question

## Name and affiliation
Michael Campanelli
Executive Director of Business Development
[Prominent Edge, LLC](https://prominentedge.com/)

## Section of RFI documents
**Document:** RFQ - cloud.gov support services FINAL.pdf
**Section:** 4.2.2 Phase 2 - Oral Interview  

## Question/Comment
If a contingent hire would like to participate in the Oral Interviews, is that permissible?

**Comment by JosephCDorsey** [comment]
That is permissible

**Comment by icamp16** [comment]
Thank you for such a prompt response.
