### ISSUE TITLE
Question:  Personnel Security Clearance Requirement

### ISSUE THREAD

**Issue by dandunlapctc** [18F/tts-buy-cloud-support-services#6]
Question

Dan Dunlap
Program Director
Computer Technologies Consultants, Inc.
Proposal Manager for this solicitation 

Attachment A - PWS - Section 5

Are there any security requirements (e.g. active Secret) for the personnel?

Thank you!

**Comment by mogul** [comment]
The maximum level of clearance that employees on the team hold currently is a "position of public trust" clearance. We're checking on the details for what we need to require for contractors, but it will not exceed that level, or an equivalent. Does that answer your question sufficiently?

(program manager for cloud.gov)

**Comment by dandunlapctc** [comment]
Hi Yes, thank you very much.  Dan

Dan Dunlap
Program Director
CTC, Inc.
7927 Jones Branch Drive, Suite 5100
McLean, VA 22102

Certified Small Business
O: 240-547-0095
F: 240-374-7024
https://www.usa-ctc.com <http://www.usa-ctc.com/>

<https://www.facebook.com/ComputerTechnologiesConsultants?ref=hl>
<https://twitter.com/CTC_IT_Services>
