### ISSUE TITLE
US Citizenship

### ISSUE THREAD

**Issue by icamp16** [18F/tts-buy-cloud-support-services#7]
# Question

## Name and affiliation
Michael Campanelli
Executive Director of Business Development
[Prominent Edge, LLC](https://prominentedge.com/) 

## Section of RFI documents
**Document:** Attachment A - PWS - cloud.gov support services FINAL 02082019.pdf
**Section:** 5.0 Program Assumptions and Constraints

## Question/Comment
I know the "security clearance" question has been asked, but I would like to be clear on citizenship. 
 Is US Citizenship (or other status) a requirement for all/any personnel?  Thank you.

**Comment by mogul** [comment]
Thanks for your patience... We've uploaded [a consolidated Q&A document](https://github.com/18F/tts-buy-cloud-support-services/blob/master/solicitation_documents/20190220%20-%20Consolidation%20of%20Questions%20and%20Answers.pdf) that includes answers to this and other questions. (Note the submission deadline was extended Monday the 25th.)
