### ISSUE TITLE
TechFlow - Multiple Questions

### ISSUE THREAD

**Issue by vroach5** [18F/tts-buy-cloud-support-services#8]
# Question/Comment

## Name and affiliation
Vivian Roach
Contracts Assistant
TechFlow, Inc. 
## Section of RFI documents
Identified for each question below.

## Question/Comment
1.	 Attachment A - PWS Section 3.0, Project Scope identifies 6,000 labor hours to assist with operations, maintenance and improvement of the cloud.gov platform.  Is it accurate to say that the 6,000 hours will likely be spent in Tasks 1 through 6?  

2.	Referencing PWS section 3.1 Core Tasks and the pricing excel file; Are bidders to price the optional Tasks 7 through 13?

3.	Will the evaluated price be the total of all optional periods, including pricing of optional tasks for each optional period?  

4.	Under RFQ Section 4.2.1, Criteria 3 (Page 7), are we correct in assuming that the government desires that the 3+ years of experience is required for cloud foundry and related tools?

5.	Mod 1 to the RFQ added FAR clause 52.232-22, Limitation of Funds. This clause is appropriate for a cost type contract, not a Labor Hour contract. We respectfully suggest that this clause is not appropriate for the type of contract identified in the RFQ. 

6.	The eBuy RFQ11349024 shows a proposal due date of 2/22/19 at 5:00PM EST; In the RFQ documents, the time is listed as 4:00PM EST on 2/22/19. Please confirm the time deadline.

**Comment by mogul** [comment]
Thanks for your patience... We've uploaded [a consolidated Q&A document](https://github.com/18F/tts-buy-cloud-support-services/blob/master/solicitation_documents/20190220%20-%20Consolidation%20of%20Questions%20and%20Answers.pdf) that includes answers to this and other questions. (Note the deadline was extended Monday the 25th.)
