### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by sangita-subramanian** [18F/tts-buy-cloud-support-services#9]
# Question/Comment

## Name and affiliation
Sangita Subramanian
VP/COO OM Group Inc

## Section of RFI documents
Cover Page

## Question/Comment
The cover page says: Contract Vehicle: GSA Schedule 70 Special Item Number (SIN) 132 51 Information
Technology Professional Services & SIN 132 40 Cloud Computing Services.
Is it either/or SIN 132 51, SIN 132 40? or are both SINs required?

## Section of RFI documents
RFQ Section 4.2.1

## Question/Comment
Would the government consider equivalent past performance experience if not on specifically cloud foundry-based platform?  For instance, Red hat’s open shift is an equivalent PaaS -platform. Similarly, Azure provides a PaaS environment to easily deploy & manage web applications. We have relevant experience to fully support the core requirements provided in the PWS using our alternative PaaS platform experience(such as OpenShift, Azure PaaS & AWS) and we request the government to consider this equivalent experience for past performance.

**Comment by mogul** [comment]
We've uploaded [a consolidated Q&A document](https://github.com/18F/tts-buy-cloud-support-services/blob/master/solicitation_documents/20190220%20-%20Consolidation%20of%20Questions%20and%20Answers.pdf) that includes answers to this and other questions.

**Comment by mogul** [comment]
(Note the submission deadline was extended Monday the 25th.)
